In [5]:
# 1.Write a NumPy program to get the numpy version and show numpy build configuration.

import numpy as np
print (np.__version__)
print (np.show_config())

1.19.4
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
None


In [6]:
# 2. Write a NumPy program to  get help on the add function.

import numpy as np
print (np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [7]:
# 3. Write a NumPy program to test whether none of the elements of a given array is zero.

import numpy as np
arr_1 = [1, 2, 3, 4, 0]
arr_2 = [4, 6, 7, 9]
print ("First array:", arr_1)
print ("The array contains 0 as its element:", np.all(arr_1))
print ("Second array:", arr_2)
print ("The array contains 0 as its element:", np.all(arr_2))

First array: [1, 2, 3, 4, 0]
The array contains 0 as its element: False
Second array: [4, 6, 7, 9]
The array contains 0 as its element: True


In [10]:
# 4. Write a NumPy program to test whether any of the elements of a given array is non-zero.

import numpy as np
arr_1 = [1, 2, 3, 4, 0]
arr_2 = [0, 0, 0, 0]
print ("First array:", arr_1)
print ("The array contains all non-zero element:", np.any(arr_1))
print ("Second array:", arr_2)
print ("The array contains all non-zero element:", np.any(arr_2))

First array: [1, 2, 3, 4, 0]
The array contains all non-zero element: True
Second array: [0, 0, 0, 0]
The array contains all non-zero element: False


In [12]:
# 5. Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a Number). 

import numpy as np
arr = [1, 2, np.nan, np.inf, 0]
print ("Given array:", arr)
print ("Finiteness of the array:", np.isfinite(arr))

Given array: [1, 2, nan, inf, 0]
Finiteness of the array: [ True  True False False  True]


In [18]:
# 6. Write a NumPy program to test element-wise for positive or negative infinity. 

import numpy as np
arr = [1, 2, np.nan, -np.inf, 0]
print ("Given  array:", arr)
print ("Check for positive infinity:", np.isneginf(arr))
print ("Check for neagtive infinity:", np.isposinf(arr))

Given  array: [1, 2, nan, -inf, 0]
Check for positive infinity: [False False False  True False]
Check for neagtive infinity: [False False False False False]


In [19]:
# 7. Write a NumPy program to test element-wise for NaN of a given array.

import numpy as np
arr = [1, 2, np.nan, -np.inf, 0]
print ("Given  array:", arr)
print ("Check for NaN elements:", np.isnan(arr))

Given  array: [1, 2, nan, -inf, 0]
Check for NaN elements: [False False  True False False]


In [24]:
# 8. Write a NumPy program to test element-wise for complex number, real number of a given array. Also test whether a given number is a scalar type or not.

import numpy as np
arr = [1, 2, np.nan, 5+6j, 0]
print ("Given array:", arr)
print ("Check for complex numbers:", np.iscomplex(arr))
print ("Check for real numbers:", np.isreal(arr))
print ("Check for scalar type number:", np.isscalar(21))
print ("Check for scalar type number:", np.isscalar([21]))

Given array: [1, 2, nan, (5+6j), 0]
Check for complex numbers: [False False False  True False]
Check for real numbers: [ True  True  True False  True]
Check for scalar type number: True
Check for scalar type number: False


In [25]:
# 9. Write a NumPy program to test whether two arrays are element-wise equal within a tolerance.

import numpy as np
print ("Checking whether two arrays are element wise equal within a tolerance")
print (np.allclose([1e10, 1e-7], [1.00001e10, 1e-8]))
print (np.allclose([1.0, np.nan], [1.0, np.nan], equal_nan=True))

Checking whether two arrays are element wise equal within a tolerance
False
True


In [26]:
# 10. Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.

import numpy as np
arr_1 = [1, 2, 3]
arr_2 = [7, 0, 3]
print ("First array:", arr_1)
print ("Second array:", arr_2)
print ("Comparison - greater:", np.greater(arr_1, arr_2))
print ("Comparison - greater or equal:", np.greater_equal(arr_1, arr_2))
print ("Comparison - less:", np.less(arr_1, arr_2))
print ("Comparison - less or equal:", np.less_equal(arr_1, arr_2))

First array: [1, 2, 3]
Second array: [7, 0, 3]
Comparison - greater: [False  True False]
Comparison - greater or equal: [False  True  True]
Comparison - less: [ True False False]
Comparison - less or equal: [ True False  True]


In [3]:
# 11. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given arrays.

import numpy as np
arr_1 = np.array ([1, 2, 3, 5, 0, 100])
arr_2 = np.array ([7, 0, 3, 5, 9, 00.0000001])
print ("Array 1:", arr_1)
print ("Array 2:", arr_2)
print ("Comparison - equal:", np.equal(arr_1, arr_2))
print ("Comparison on the basis of tolerance - equal:", np.allclose(arr_1, arr_2))

Array 1: [  1   2   3   5   0 100]
Array 2: [7.e+00 0.e+00 3.e+00 5.e+00 9.e+00 1.e-07]
Comparison - equal: [False False  True  True False False]
Comparison on the basis of tolerance - equal: False


In [7]:
# 12. Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array. 

import numpy as np
arr = np.array([1, 7, 13, 105])
print ("Given array:", arr)
print ("Size of the memory occupied by the array: {} bytes".format(arr.size * arr.itemsize))

Given array: [  1   7  13 105]
Size of the memory occupied by the array: 16 bytes


In [8]:
# 13. Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

import numpy as np
arr_1 = np.zeros(10)
print ("Array of 10 zeros:", arr_1)
arr_2 = np.ones(10)
print ("Array of 10 ones:", arr_2)
arr_3 = np.ones(10) * 5
print ("Array of 10 fives:", arr_3)

Array of 10 zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array of 10 ones: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Array of 10 fives: [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [13]:
# 14. Write a NumPy program to create an array of the integers from 30 to70. 

import numpy as np
arr = np.arange(30, 71)
print ("Array of integers from 30 to 70:")
print (arr)

Array of integers from 30 to 70:
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [14]:
# 15. Write a NumPy program to create an array of all the even integers from 30 to 70.

import numpy as np
arr = np.arange(30, 71, 2)
print ("Array of even integers from 30 to 70:")
print (arr)

Array of even integers from 30 to 70:
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [15]:
# 16. Write a NumPy program to create a 3x3 identity matrix.

import numpy as np
arr = np.identity(3)
print ("3x3 indentity matrix:")
print (arr)

3x3 indentity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
# 17. Write a NumPy program to generate a random number between 0 and 1.

import numpy as np
a = np.random.normal(0, 1, 1)
print ("Random number between 0 and 1:", a)

Random number between 0 and 1: [0.30962289]


In [20]:
# 18. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

import numpy as np
arr = np.random.normal(0, 1, 15)
print ("Array of 15 random number:")
print (arr)

Array of 15 random number:
[-1.56596658 -1.45991983 -0.83513961  0.49416174 -1.57492818 -0.93395741
 -0.11782487 -2.34530617 -1.44984414  0.87426553 -0.25318445  0.2336556
  0.87120175  1.36040524  0.53869889]


In [26]:
# 19. Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.

import numpy as np
vector = np.arange(15, 56)
print ("Array in range 15 to 55:")
print (vector)
print ("Array excluding 15 and 55:")
print (vector[1:-1])

Array in range 15 to 55:
[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]
Array excluding 15 and 55:
[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


In [30]:
# 20. Write a NumPy program to create a 3X4 array using and iterate over it.

import numpy as np
arr = np.arange(10, 22).reshape(3, 4)
print ("3x4 array:")
print (arr)
print ("Using and iterate:")
for i in np.nditer(arr):
    print (i, end = " ")

3x4 array:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Using and iterate:
10 11 12 13 14 15 16 17 18 19 20 21 