In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
# 1D array
arr = np.array([1, 4, 5, 6, 7])
arr

array([1, 4, 5, 6, 7])

In [4]:
arr = np.array((1, 4, 5, 6, 7))
arr

array([1, 4, 5, 6, 7])

In [5]:
# 2D array
arr = np.array([[1, 4, 5], [2, 7, 5]])
arr

array([[1, 4, 5],
       [2, 7, 5]])

In [7]:
# 3D
arr = np.array([[[1, 4, 5], [2, 7, 5], [8, 9, 10]]])
arr

array([[[ 1,  4,  5],
        [ 2,  7,  5],
        [ 8,  9, 10]]])

In [8]:
arr.ndim

3

In [9]:
arr.shape

(1, 3, 3)

In [10]:
arr = np.array([1, 4, 5, 6, 7])
arr

array([1, 4, 5, 6, 7])

In [11]:
arr [2]

5

In [12]:
arr = np.array([[1, 4, 5], [2, 7, 5]])
arr

array([[1, 4, 5],
       [2, 7, 5]])

In [13]:
arr [0, 1] # Row, column

4

In [14]:
arr [0, :] # First row

array([1, 4, 5])

In [15]:
arr [:, -1] # Last column

array([5, 5])

In [16]:
arr = np.array([1, 2, 3, 4, 5, 6])

In [17]:
np.cos(arr)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029])

In [18]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ])

In [19]:
np.tan(arr)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501,
       -0.29100619])

In [20]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947])

In [21]:
np.mean(arr)

3.5

In [22]:
np.median(arr)

3.5

In [23]:
np.std(arr)

1.707825127659933

In [24]:
np.exp(arr)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 , 403.42879349])

In [25]:
arr_1 = np.array([2, 4, 6, 8, 10, 12])
arr_2 = np.array([1, 3, 5, 7, 9, 11])


In [26]:
arr_1 + arr_2

array([ 3,  7, 11, 15, 19, 23])

In [27]:
arr_1 - arr_2

array([1, 1, 1, 1, 1, 1])

In [28]:
arr_1 * arr_2

array([  2,  12,  30,  56,  90, 132])

In [29]:
arr_1 / arr_2

array([2.        , 1.33333333, 1.2       , 1.14285714, 1.11111111,
       1.09090909])

In [30]:
arr_1 / 0

<ipython-input-30-c41d69d122d7>:1: RuntimeWarning: divide by zero encountered in true_divide
  arr_1 / 0


array([inf, inf, inf, inf, inf, inf])

In [31]:
0 / arr_2

array([0., 0., 0., 0., 0., 0.])

In [34]:
arr = np.ones(5)
arr

array([1., 1., 1., 1., 1.])

In [35]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [37]:
np.zeros(3)

array([0., 0., 0.])

In [38]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [39]:
# Identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [40]:
arr = np.array([1.4325, 3.0786, 4.56])
np.round(arr)

array([1., 3., 5.])

In [41]:
np.round(arr, 2)

array([1.43, 3.08, 4.56])

In [42]:
# Linerarly spaced numbers
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [45]:
# 
a = np.arange(1, 10, 2)

In [46]:
a

array([1, 3, 5, 7, 9])

In [48]:
a.shape

(5,)

In [51]:
a.reshape ((1, 5))

array([[1, 3, 5, 7, 9]])

In [52]:
a

array([1, 3, 5, 7, 9])

In [53]:
# To get maximum value of the array
np.max(a)

9

In [54]:
arr = np.array([[1, 4, 5], [2, 7, 5]])
arr

array([[1, 4, 5],
       [2, 7, 5]])

In [55]:
np.max(arr)

7

In [56]:
arr.ravel()

array([1, 4, 5, 2, 7, 5])

In [57]:
a3 = np.arange(1, 11)

In [58]:
a3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
a4 = a3.reshape((2, 5))

In [60]:
a4

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [62]:
a4.shape

(2, 5)

In [63]:
np.max(a4, axis = 0) # 0 means column

array([ 6,  7,  8,  9, 10])

In [64]:
np.max(a4, axis = 1) # 1 means row

array([ 5, 10])

In [65]:
a

array([1, 3, 5, 7, 9])

In [66]:
np.argmax(a)

4

In [68]:
a4

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [71]:
list(a4)

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]

In [72]:
np.full(a4.shape, fill_value=22)

array([[22, 22, 22, 22, 22],
       [22, 22, 22, 22, 22]])

In [73]:
a4

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [74]:
# Boolean mask
a4 > 8

array([[False, False, False, False, False],
       [False, False, False,  True,  True]])

In [76]:
a4 [a4 > 8]

array([ 9, 10])

In [77]:
arr_1 = np.array([2, 4, 5, 6, 7, 8], dtype = "int64")

In [78]:
arr_1

array([2, 4, 5, 6, 7, 8], dtype=int64)

In [79]:
arr_1.dtype

dtype('int64')

In [80]:
a4

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [81]:
a4 [0, :]

array([1, 2, 3, 4, 5])

In [82]:
a4 [0, :] = 41

In [83]:
a4

array([[41, 41, 41, 41, 41],
       [ 6,  7,  8,  9, 10]])